version: "3"
services:
  backend:
    image: 'reminder-app:latest'
    container_name: reminder-app
    working_dir: /app
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SERVER_PORT:
      SERVER_ADDRESS_IP:
      SERVER_SSL_ENABLED:

      POSTGRES_URL:
      POSTGRES_USERNAME:
      POSTGRES_PASSWORD:

      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:

      MAIL_HOST:
      MAIL_PORT:
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_SMTP_STARTTLS_ENABLED:
      MAIL_SMTP_AUTH_ENABLED:
      MAIL_SMTP_CONNECTION_TIMEOUT_ENABLED:
      MAIL_SMTP_CONNECTION_TIMEOUT_MS:
      MAIL_SMTP_CONNECTION_WRITE_TIMEOUT_MS:

      TELEGRAM_BOT_USERNAME:
      TELEGRAM_BOT_TOKEN:

  db:
    image: postgres
    container_name: reminder-db
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data